### PR TITLE
Load the arp-camera module automatically when the arp module is loaded

### PR DESCRIPTION
**Pull request by linusnielsen**
Add a modprobe.d conf file that loads the arp-camera module automatically.

### CODE REVIEW

**Comment by FlorentRevest** [comment]
Don't you need to add this file to a SOURCE_URI somewhere?

**Review by TSAnsari — APPROVED** [review]

**Comment by sashko** [comment]
@linusnielsen ping.

**Comment by linusnielsen** [comment]
@sashko yes? Do I need to do anything more?

**Comment by sashko** [comment]
@linusnielsen doesn't seem like; feel free to push it if you still need it, otherwise close PR, please.

**Comment by linusnielsen** [comment]
@sashko I'm afraid I don't have commit access, so I can't merge it myself.

**Pull request merged**
